name: 🚀 Publish to NPM

# Publish NPM package on release.
on:
  release:
    types:
      - created

jobs:
  publish:
    name: 🚀 Publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        name: 💦 Checkout code
      - uses: actions/setup-node@v1
        name: 🛑 Setup Node.js v12
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: yarn install
        name: 🔨 Install packages
      - run: yarn test
        name: ✅ Run tests
      - run: yarn test:coverage
        name: 🌗 Check coverage
      - run: npm publish --access public
        name: 🚀 Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}